[calendars]
Grady = "https://calendar.google.com/calendar/ical/graydon.selanders%40gmail.com/private-333d903884e753194879cbfc0b35f435/basic.ics"

# Gianni = "https://calendar.google.com/calendar/ical/.../basic.ics"